---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install necessary utils
      package:
        name: 
          - jq
          - sqlite
          - libpam-script
    - name: add passport user
      user:
       name: passport
       comment: Hydra Passport
    - name: copy libpam-script file for passport
      copy:
        src: files/pam_script_auth
        dest: /usr/share/libpam-script
        mode: '0755'
    - name: create bin dir for passport
      file:
        path: /home/passport/bin
        state: directory
        owner: root
        group: passport
        mode: '0750'
    - name: copy passport_ssh_auth.sh file to passport/bin
      copy:
        src: files/passport_ssh_auth.sh
        dest: /home/passport/bin
        owner: root
        group: passport
        mode: '0750'
    - name: copy passport subs to passport home
      copy:
        src: files/passport_subs
        dest: /home/passport/.passport_subs
        group: passport
        mode: '0640'
    - name: set passport homedir perms
      file:
        path: /home/passport
        state: directory
        owner: root
        group: passport
        mode: '0750'
    - name: create condition for sshd authorized keys command
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysCommand\s.*$'
        state: absent
      check_mode: yes
      changed_when: false
      register: authkcmd
    - name: set sshd authorized keys command
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'AuthorizedKeysCommand /home/passport/bin/passport_ssh_auth.sh'
      when: not authkcmd.found
    - name: create condition for sshd authorized keys command user
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysCommandUser\.s*$'
        state: absent
      check_mode: yes
      changed_when: false
      register: authkcusr
    - name: set sshd authorized keys command user
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'AuthorizedKeysCommandUser passport'
      when: not authkcusr.found
    - name: restart sshd
      service:
        name: sshd
        state: restarted

